### PR TITLE
Fix http request

### PR DESCRIPTION
**Pull request by bastian-src**
An error was thrown since `base64.b64encode` needs bytes as input, not string.
&rarr; Add str to byte conversion before performing base64 encoding

### CODE REVIEW

**Comment by m-bucher** [comment]
I did a quick check and this is one of the problems between python2 and python3:

On python3 the solution implemented by this PR works:
```python
import base64
a = "日本語"
base64.b64encode(a.encode("UTF-8"))
# => '5pel5pys6Kqe'
base64.b64encode(a)
# => TypeError: a bytes-like object is required, not 'str'
```
On python2 the original implementation works:
```python
import base64
a = "日本語"
base64.b64encode(a)
# => '5pel5pys6Kqe'
base64.b64encode(a.encode("UTF-8"))
# => UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)
```

**Comment by bastian-src** [comment]
Thanks @m-bucher for the hint!
It totally makes sense. The function needs a byte-type string and Python 2 uses bytes by default. Python 3 uses unicode strings and therefore must be converted. I would suggest a quick check, whether the given string is an instance of bytes already and, if not, encode it. What do you think about it?

**Comment by bastian-src** [comment]
Implemented as suggested.

**Review by m-bucher — APPROVED** [review]
Looks good

**Pull request merged**
